import { gql } from "@apollo/client";

export const GET_USER_DATA= gql(`
query getUserData{
    getUserData{
        data{
            id
            clientId
            firstName
            lastName
            patronymic
            birthDate
            gender
            email
            phoneNumber
            additionalPhoneNumber
            docType
            docSeries
            docNumber
            docGivingDepName
            docGivingDepCode
            docDate
            docRegAddress
            snils
            inn
            cityId
            addressFull
            addressMisKladrId
            longitude
            latitude
            zoneNumber
            defaultMedicalCenterId
            loginPhoneNumber
            isVerified
            infoWayId
            notificationTime
            prefNotificationContactId
            isActive
            created
            city{
                id
                clientId
                name
                isActive
            }
            defaultMedicalCenter{
                id
                clientId
                cityId
                name
                address
                longitude
                latitude
                description
                inn
                bankBic
                settlementAccount
                correspondentAccount
                kpp
                isActive
                logo
                websiteUrl
                phoneFax
                dmsPhone
                workTime
                collectionTestsTime
                vaccinationTime
                city{
                    id
                    clientId
                    name
                    isActive
                }
            }
            infoWay{
                id
                clientId
                name
                description
                isActive
            }
            prefNotificationContact{
                id
                clientId
                firstName
                lastName
                patronymic
                birthDate
                gender
                email
                phoneNumber
                additionalPhoneNumber
                docType
                docSeries
                docNumber
                docGivingDepName
                docGivingDepCode
                docDate
                docRegAddress
                snils
                inn
                cityId
                addressFull
                addressMisKladrId
                longitude
                latitude
                zoneNumber
                defaultMedicalCenterId
                loginPhoneNumber
                isVerified
                infoWayId
                notificationTime
                prefNotificationContactId
                isActive
                created
                city{
                    id
                    clientId
                    name
                    isActive
                }
                defaultMedicalCenter{
                    id
                    clientId
                    cityId
                    name
                    address
                    longitude
                    latitude
                    description
                    inn
                    bankBic
                    settlementAccount
                    correspondentAccount
                    kpp
                    isActive
                    logo
                    websiteUrl
                    phoneFax
                    dmsPhone
                    workTime
                    collectionTestsTime
                    vaccinationTime
                }
                infoWay{
                    id
                    clientId
                    name
                    description
                    isActive
                }
                prefNotificationContact{
                    id
                    clientId
                    firstName
                    lastName
                    patronymic
                    birthDate
                    gender
                    email
                    phoneNumber
                    additionalPhoneNumber
                    docType
                    docSeries
                    docNumber
                    docGivingDepName
                    docGivingDepCode
                    docDate
                    docRegAddress
                    snils
                    inn
                    cityId
                    addressFull
                    addressMisKladrId
                    longitude
                    latitude
                    zoneNumber
                    defaultMedicalCenterId
                    loginPhoneNumber
                    isVerified
                    infoWayId
                    notificationTime
                    prefNotificationContactId
                    isActive
                    created
                    addressMisKladr{
                        id
                        clientId
                        clientUserId
                        tag
                        luid
                        region
                        regionCode
                        area
                        areaCode
                        city
                        cityCode
                        town
                        townCode
                        street
                        streetCode
                        house
                        corp
                        flat
                        note
                        status
                        livesLuId
                        houseCode
                    }
                }
            }
            addressMisKladr{
                id
                clientId
                clientUserId
                tag
                luid
                region
                regionCode
                area
                areaCode
                city
                cityCode
                town
                townCode
                street
                streetCode
                house
                corp
                flat
                note
                status
                livesLuId
                houseCode
            }
        }
        statusCode
        details
    }
}
`)