import { gql } from "../../../__generated__/gql";

export const GET_SERVICES = gql(`
query getServices($filteringAttrs: ServiceInput, $orderingAttrs: ServiceInput, $skip: Int, $limit: Int, $descSorting: Boolean){
    getServices(filteringAttrs: $filteringAttrs, orderingAttrs: $orderingAttrs, skip: $skip, limit: $limit, descSorting: $descSorting){
        data{
            id
            clientId
            serviceTypeId
            serviceGroupId
            nameForStaff
            nameForMz
            nameForLk
            fullDescription
            appliedMethod
            preparationRules
            shortDescription
            comment
            mzCode
            executionTime
            nursesExecutionTime
            minimalAge
            maximalAge
            gender
            isUrgent
            isForHomeOnly
            selectedServiceNotification
            isComplexService
            clientServiceCode
            isActive
            serviceType{
                id
                clientId
                name
                description
                isActive
            }
            serviceGroup{
                id
                clientId
                name
                viewName
                description
                clientServiceGroupCode
                levelSortingCode
                isActive
                xmembers{
                    id
                    clientId
                    name
                    viewName
                    description
                    clientServiceGroupCode
                    levelSortingCode
                    isActive
                    xmembers{
                        id
                        clientId
                        name
                        viewName
                        description
                        clientServiceGroupCode
                        levelSortingCode
                        isActive
                        path
                    }
                    path
                }
                path
            }
        }
        statusCode
        details
    }
}
`);