import { gql } from "../../../__generated__/gql";

export const GET_SERVICES = gql(`
query getServices($filteringAttrs: ServiceInput, $orderingAttrs: ServiceInput, $skip: Int, $limit: Int, $descSorting: Boolean){
  getServices(filteringAttrs: $filteringAttrs, orderingAttrs: $orderingAttrs, skip: $skip, limit: $limit, descSorting: $descSorting){
      data{
          id
          clientServiceId
          serviceTypeId
          serviceGroupId
          nameForStaff
          nameForMz
          nameForLk
          fullDescription
          appliedMethod
          preparationRules
          shortDescription
          comment
          mzCode
          executionTime
          nursesExecutionTime
          minimalAge
          maximalAge
          gender
          isUrgent
          isForHomeOnly
          selectedServiceNotification
          isComplexService
          clientServiceCode
          isActive
          serviceType{
              id
              clientServiceTypeId
              name
              description
              isActive
          }
          serviceGroup{
              id
              clientServiceGroupId
              name
              viewName
              description
              clientServiceGroupCode
              levelSortingCode
              isActive
              xmembers{
                  id
                  clientServiceGroupId
                  name
                  viewName
                  description
                  clientServiceGroupCode
                  levelSortingCode
                  isActive
                  xmembers{
                      id
                      clientServiceGroupId
                      name
                      viewName
                      description
                      clientServiceGroupCode
                      levelSortingCode
                      isActive
                      path
                  }
                  path
              }
              path
          }
      }
      statusCode
      details
  }
}
`);